# Spring properties
spring:
  application:
     name: measurement-utilities-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.206.97:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  name: Instance 1